# user agents to use
choices_user_agents = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 11.2; rv:89.0) Gecko/20100101 Firefox/89.0',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15A372 Safari/604.1',
    'Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.2 Mobile/15A217 Safari/604.1',
    'Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Mobile Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15A372 Safari/604.1',
    'Mozilla/5.0 (Linux; Android 9; Pixel 3 XL Build/PQ2A.190305.002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36',
    'Mozilla/5.0 (Linux; Android 9; SM-G960F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36',
    'Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15A372 Safari/604.1'
    # Add more user agents here
]

choices_referers = [
    'https://www.google.com/',
    'https://www.bing.com/',
    'https://www.yahoo.com/',
    'https://www.duckduckgo.com/',
    'https://www.baidu.com/',
    'https://www.yandex.com/',
    'https://www.ask.com/',
    'https://www.aol.com/',
    'https://www.ecosia.org/',
    'https://www.startpage.com/',
    'https://www.qwant.com/',
    'https://www.searchencrypt.com/',
    'https://www.facebook.com/',
    'https://www.twitter.com/',
    'https://www.instagram.com/',
    'https://www.linkedin.com/',
    'https://www.reddit.com/',
    'https://www.pinterest.com/',
    'https://www.tumblr.com/',
    'https://www.quora.com/',
    'https://news.ycombinator.com/',
    'https://www.medium.com/',
    'https://www.nytimes.com/',
    'https://www.theguardian.com/',
    'https://www.bbc.com/',
    'https://www.cnn.com/',
    'https://www.forbes.com/',
    'https://www.bloomberg.com/',
    'https://www.wired.com/',
    'https://www.theverge.com/',
    'https://www.techcrunch.com/',
    'https://www.businessinsider.com/',
    'https://www.cnet.com/',
    'https://www.engadget.com/',
    'https://www.wikipedia.org/',
    'https://www.imdb.com/',
    'https://www.stackoverflow.com/',
    'https://www.github.com/',
    'https://www.medium.com/',
    'https://www.stackexchange.com/',
    'https://www.producthunt.com/',
    'https://www.netflix.com/',
    'https://www.hulu.com/',
    'https://www.spotify.com/',
    'https://www.apple.com/',
    'https://www.microsoft.com/',
    'https://www.amazon.com/',
    'https://www.ebay.com/',
    'https://www.alibaba.com/',
    'https://www.ted.com/',
    'https://www.kickstarter.com/',
    'https://www.airbnb.com/',
    'https://www.booking.com/',
    'https://www.expedia.com/',
    'https://www.tripadvisor.com/',
    'https://www.nike.com/',
    'https://www.adidas.com/',
    'https://www.walmart.com/',
    'https://www.target.com/',
    'https://www.bestbuy.com/',
    'https://www.costco.com/',
    'https://www.zillow.com/',
    'https://www.trulia.com/',
    'https://www.realtor.com/',
    'https://www.autotrader.com/',
    'https://www.cars.com/',
    'https://www.opentable.com/',
    'https://www.ubereats.com/',
    'https://www.grubhub.com/',
    'https://www.doordash.com/',
    'https://www.groupon.com/',
    'https://www.etsy.com/',
    'https://www.twitch.tv/',
    'https://www.slideshare.net/',
    'https://www.flickr.com/',
    'https://www.dailymotion.com/',
    'https://www.vimeo.com/',
    'https://www.soundcloud.com/',
    'https://www.mixcloud.com/',
    'https://www.deviantart.com/',
    'https://www.behance.net/',
    'https://www.dribbble.com/',
    'https://www.trello.com/',
    'https://www.slack.com/',
    'https://www.airtable.com/',
    'https://www.zoom.us/',
    'https://www.dropbox.com/',
    'https://www.box.com/',
    'https://www.salesforce.com/',
    'https://www.notion.so/',
    'https://www.microsoftonline.com/',
    'https://www.spotify.com/',
    'https://www.apple.com/itunes/',
    'https://www.soundcloud.com/',
    'https://www.mixcloud.com/',
    'https://www.grammarly.com/',
    'https://www.canva.com/',
    'https://www.udemy.com/',
    'https://www.coursera.org/',
    'https://www.edx.org/',
    'https://www.codecademy.com/',
    'https://www.khanacademy.org/',
    'https://www.hackerrank.com/',
    'https://www.hackerearth.com/',
    'https://www.medium.com/',
    'https://www.dev.to/',
    'https://www.hashnode.com/',
    'https://www.ted.com/',
    'https://www.instructables.com/'
    # Add more referers here if needed
]